# Use Tomcat 9 as base image
FROM tomcat:9.0

# Maintainer info (optional)
LABEL maintainer="Amarjeet <your-email@example.com>"

# Remove default ROOT app (optional, keeps container clean)
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your WAR file into Tomcat webapps directory
COPY target/javaApp.war /usr/local/tomcat/webapps/javaApp.war

# Expose Tomcat default port
EXPOSE 8080

